# Generated by Django 2.1.4 on 2018-12-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpringRate', models.IntegerField(max_length=300)),
                ('FrontCompression', models.IntegerField(max_length=30)),
                ('FrontRebound', models.IntegerField(max_length=30)),
                ('RearHighSpeedCompression', models.IntegerField(max_length=30)),
                ('RearLowSpeedCompression', models.IntegerField(max_length=30)),
                ('RearRebound', models.IntegerField(max_length=30)),
                ('Sag', models.IntegerField(max_length=30)),
                ('Notes', models.TextField()),
            ],
        ),
    ]
